### ISSUE TITLE
Title: Set Up Fink-Broker Environment for Debugging Stackable Operator ArgoCD Issue

### ISSUE THREAD

**Issue by fjammes** [astrolabsoftware/fink-broker#936]
**Describe the issue**
I will set up a Fink-broker environment dedicated to debugging the stackable operator issue referenced in [hdfs-operator #626](https://github.com/stackabletech/hdfs-operator/issues/626).

**Expected behaviour**
The environment should enable effective reproduction and debugging of the ArgoCD issue to identify its root cause and potential solutions.

**Actual behaviour**
A hack has been implemented in fink-cd for argocdCD to work

**To Reproduce**

Remove section below from `fink-cd/apps/templates/stackable-hadoop-operators.yaml`:
```
ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: "CustomResourceDefinition"
    # Default values for these fields appears explicitely in desired state but are removed from actual state
    jqPathExpressions:
    - .spec.names.categories | select(. == [])
    - .spec.names.shortNames | select(. == [])
    - .spec.versions[].additionalPrinterColumns | select(. == [])
```

System Information:

Operating System: Kubernetes 1.30
Fink Version: v3.1.3-rc1+
Occurred on which branch and with what commit: [master-abc456d]

Additional context
This environment will help isolate the root cause of the issue, facilitating a more focused debugging process and potentially leading to a resolution and a PR for [hdfs-operator #626](https://github.com/stackabletech/hdfs-operator/issues/626).
